sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull ocaml/opam2:debian-9
  - docker build -t smoosh .

script:
  - docker build -t smoosh-test -f Dockerfile.test .
  - docker build -t smoosh-web -f Dockerfile.web .
