dist: xenial

language: generic

matrix:
  include:
  - os: osx
    osx_image: xcode11.3
    env: OCAML_VERSION=4.09
  - os: freebsd
    env: OCAML_VERSION=4.09
  - os: linux
    env: OCAML_VERSION=4.09
  - os: linux
    env: OCAML_VERSION=4.09 INSTALL_LOCAL=1
  - os: linux
    env: OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
  allow_failures:
  - os: freebsd
    env: OCAML_VERSION=4.09


cache:
  directories:
    - $HOME/.opam
    - $HOME/.rvm

addons:
  apt:
    packages:
      - autoconf
      - autotools-dev
      - libtool
      - pkg-config
      - libffi-dev
      - ruby-full
      - ruby-bundler
  homebrew:
    packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - libffi
      - ruby
      - ruby-build

before_install:
  # INSTALL WEB SERVER DEPS
  - gem install -v 0.9.0 childprocess 
  - gem install -v 2.0.5 sinatra
  - gem install -v 2.0.5 sinatra-contrib
  - gem install -v 1.7.2 thin

  # INSTALL OPAM
  - test -e .travis-ocaml.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh  

  # INSTALL DEPS
  - opam install -y ocamlfind ocamlbuild num zarith extunix
  - (cd libdash; opam pin -y add .)

  # INSTALL lem
  - opam exec -- make -C lem
  - opam exec -- make -C lem install
  - export LEMLIB=$(pwd)/lem/library
  - export PATH="$(pwd)/lem/bin:$PATH"

install:
  # BUILD SMOOSH
  - opam exec -- make -C src all all.byte
  - export PATH="$(pwd)/src:$PATH"
  
script:
  # TEST SMOOSH
  - make -C src/ test
  - TEST_DEBUG=1 make -C tests/ test

  # BUILD AND TEST WEB SERVER
  - (cd web; bundle install)
  - sh web/src/mk_config.sh $(pwd) >web/src/config.yml
  - cat web/src/config.yml
  - mkdir web/submissions
  - pwd
  - web/run.sh &
  - sleep 5
  - curl --fail --data-ascii @web/test.post http://localhost:2080/shtepper
