name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.10.0
          - 4.11.0
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install libdash
        run: |
          opam pin add libdash ./libdash --no-action
          opam depext libdash --yes --with-test
          opam install ./libdash
        
      - name: Build smoosh, run unit tests
        run: |
          opam exec -- make -C src all all.byte
          make -C src/ test
          
      - name: Run smoosh integration tests
        run: TEST_DEBUG=1 TEST_TIMEOUT=15 make -C tests/ test

          
        
